<!-----------------------------------
-- Plantilla HTML para la cabecera --
------------------------------------>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>P8 Idea de Empresa</title>

    <link rel="stylesheet" href="/public/css/style.css">
</head>
<body>
    <header>
        <nav class="navigation-bar"> 

        </nav>
    </header>