<!--------------------------------------------
-- Plantilla HTML para la pagina de portada --
--------------------------------------------->
<?php /* incluimos la cabecera */ include __DIR__ . '/header.phtml' ?>

<!-- Incluir el css especifico de cada pagina  -->
<link rel="stylesheet" href="./public/css/home.css">

<!-- HTML de cada pagina -->
<div class="home">
    <h1>Home</h1>
</div>

<?php /* incluimos el footer */ include __DIR__ . '/footer.phtml' ?>